name: Run Stock Tracker

on:
  schedule:
    # Schedule to run at 12:00 PM and 8:00 PM UTC every day
    - cron: "0 11,23 * * *"
  workflow_dispatch:  # Enable manual triggering

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Print current time
        run: date  # Prints the current time in the logs

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run script
        run: python stock_tracker_alerts.py
